// <auto-generated />
using System;
using BusinessObjects.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Elm Street",
                            Birthday = new DateOnly(1990, 1, 1),
                            Fullname = "John Doe",
                            Gender = "Male",
                            Password = "Password123",
                            Username = "johnDoe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue",
                            Birthday = new DateOnly(1992, 2, 15),
                            Fullname = "Jane Doe",
                            Gender = "Female",
                            Password = "Password456",
                            Username = "janeDoe"
                        },
                        new
                        {
                            Id = 3,
                            Address = "123 Elm Street",
                            Birthday = new DateOnly(1990, 1, 1),
                            Fullname = "John Doe",
                            Gender = "Male",
                            Password = "Password123",
                            Username = "johnDoe"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Elm Street",
                            Birthday = new DateOnly(1990, 1, 1),
                            Fullname = "John Doe",
                            Gender = "Male",
                            Password = "Password123",
                            Username = "johnDoe"
                        },
                        new
                        {
                            Id = 5,
                            Address = "123 Elm Street",
                            Birthday = new DateOnly(1990, 1, 1),
                            Fullname = "John Doe",
                            Gender = "Male",
                            Password = "Password123",
                            Username = "johnDoe"
                        },
                        new
                        {
                            Id = 6,
                            Address = "123 Elm Street",
                            Birthday = new DateOnly(1990, 1, 1),
                            Fullname = "John Doe",
                            Gender = "Male",
                            Password = "Password123",
                            Username = "johnDoe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
